# Setup
title:          Blushing Defeat - Bimbofication Games
tagline:        Blog, Games, Bimbofication
baseurl:      ""
paginate:     5
paginate_path: "/blog/page:num/"

# About/contact
author:
  name:       Gardamuse
  url:        http://www.blushingdefeat.com
  email:      gardamuse@blushingdefeat.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-sitemap

#Others
markdown: kramdown
future: false

collections:
  sections:
  characters:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "pages"
    values:
      title: "Blushing Defeat - Bimbofication Games"
      layout: "single-layout"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blogpost"

permalink: pretty
