# Setup
title:        Gardamuse
tagline:      NSFW Games Galore
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
future: true
