# Setup
title:        Gardamuse
tagline:      NSFW Games Galore
baseurl:      ""
paginate:     5

# About/contact
author:       Gardamuse
  name:       Gardamuse
  url:        http://gardamuse.github.io

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
future: true

collections:
  - sections
