# Setup
title:          Blushing Defeat - NSFW Bimbofication Games
header-title:   Blushing Defeat
tagline:        Blog, Games, Bimbofication
header-tagline: Blog, Games, Bimbofication
baseurl:      ""
paginate:     5
paginate_path: "/blog/page:num/"

# About/contact
author:
  name:       Gardamuse
  url:        http://www.blushingdefeat.com
  email:      gardamuse@blushingdefeat.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-sitemap

#Others
markdown: kramdown
future: false

collections:
  - sections
  - characters
  - playposts

defaults:
  - scope:
      path: ""
      type: "playposts"
    values:
      layout: "post"

permalink: pretty
