# Setup
title:        Blushing Defeat
tagline:      Gardamuse's Blog
baseurl:      ""
paginate:     5

# About/contact
author:
  name:       Gardamuse
  url:        https://gardamuse.github.io
  email:      gardamuse@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-coffeescript

#Others
markdown: kramdown
future: false

collections:
  - sections
  - characters
  - playposts

defaults:
  - scope:
      path: ""
      type: "playposts"
    values:
      layout: "post"

permalink: pretty
